[32m2024-08-20 02:40:25 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5b1e191b-07ba-4c83-abae-b269d6ff7912 - 735294 - LOGS_CAPTURED - Started capturing logs in process (pid: 735294).
[32m2024-08-20 02:40:25 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5b1e191b-07ba-4c83-abae-b269d6ff7912 - 735294 - store_prediction_data - STEP_START - Started execution of step "store_prediction_data".
[32m2024-08-20 02:40:25 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 5b1e191b-07ba-4c83-abae-b269d6ff7912 - 735294 - store_prediction_data - STEP_FAILURE - Execution of step "store_prediction_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "store_prediction_data"::

UnboundLocalError: cannot access local variable 'atlas_uri' where it is not associated with a value

Stack Trace:
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 474, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 169, in store_prediction_data
    mongo_client = pymongo.MongoClient(atlas_uri)
                                       ^^^^^^^^^
[0m
