[32m2024-08-20 02:12:08 +0000[0m - dagster - [34mDEBUG[0m - pipeline - 20261839-36c2-4e9b-ae39-ca9893c59e24 - 662144 - LOGS_CAPTURED - Started capturing logs in process (pid: 662144).
[32m2024-08-20 02:12:08 +0000[0m - dagster - [34mDEBUG[0m - pipeline - 20261839-36c2-4e9b-ae39-ca9893c59e24 - 662144 - store_prediction_data - STEP_START - Started execution of step "store_prediction_data".
[32m2024-08-20 02:12:38 +0000[0m - dagster - [34mERROR[0m - [31mpipeline - 20261839-36c2-4e9b-ae39-ca9893c59e24 - 662144 - store_prediction_data - STEP_FAILURE - Execution of step "store_prediction_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "store_prediction_data"::

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 66c3fb782c3786f4f908ebc1, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

Stack Trace:
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 474, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 178, in store_prediction_data
    returned_id = collection.insert_one(predictions).inserted_id
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/collection.py", line 698, in insert_one
    self._insert(document,
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/collection.py", line 613, in _insert
    return self._insert_one(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/collection.py", line 602, in _insert_one
    self.__database.client._retryable_write(
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1497, in _retryable_write
    with self._tmp_session(session) as s:
  File "/home/gitpod/.pyenv/versions/3.12.4/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1829, in _tmp_session
    s = self._ensure_session(session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/topology.py", line 485, in get_server_session
    self._select_servers_loop(
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
[0m
