[32m2024-08-19 23:55:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 19f9dd2f-37fe-46ab-a242-7b573062c739 - 296680 - LOGS_CAPTURED - Started capturing logs in process (pid: 296680).
[32m2024-08-19 23:55:13 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 19f9dd2f-37fe-46ab-a242-7b573062c739 - 296680 - db_crypto_transfer_transactions - STEP_START - Started execution of step "db_crypto_transfer_transactions".
[32m2024-08-19 23:55:13 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 19f9dd2f-37fe-46ab-a242-7b573062c739 - 296680 - db_crypto_transfer_transactions - STEP_FAILURE - Execution of step "db_crypto_transfer_transactions" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "db_crypto_transfer_transactions"::

AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'ConstraintException'

Stack Trace:
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 474, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 70, in db_crypto_transfer_transactions
    except conn.ConstraintException:
           ^^^^^^^^^^^^^^^^^^^^^^^^

The above exception occurred during handling of the following exception:
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "'0.1904'"

Stack Trace:
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 65, in db_crypto_transfer_transactions
    conn.sql(f"""
[0m
