[32m2024-08-20 00:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8ed211dd-20fe-46af-aaf6-85241ce1f49d - 375382 - LOGS_CAPTURED - Started capturing logs in process (pid: 375382).
[32m2024-08-20 00:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8ed211dd-20fe-46af-aaf6-85241ce1f49d - 375382 - predict_data - STEP_START - Started execution of step "predict_data".
00:27:16 - cmdstanpy - INFO - Chain [1] start processing
00:27:16 - cmdstanpy - INFO - Chain [1] done processing
[32m2024-08-20 00:27:16 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 8ed211dd-20fe-46af-aaf6-85241ce1f49d - 375382 - predict_data - STEP_FAILURE - Execution of step "predict_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "predict_data"::

KeyError: "['y'] not in index"

Stack Trace:
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 474, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 105, in predict_data
    forecast_dict = forecast[["ds", "y"]].to_dict()
                    ~~~~~~~~^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
[0m
